renv::init()
packs <- c("lubridate", "plotly", "RColorBrewer", "shiny", "tidyverse", "viridis")
renv::install(packs)
library(lubridate)
library(plotly)
library(RColorBrewer)
library(shiny)
library(tidyverse)
library(viridis)
renv::snapshot()
